llm = "gpt-4"
user_index_dir = "user_context_index"
agent_execution_mode = "interactive"
agent_type = "zero-shot-react-description"
eval_sentence = "eval_sentence/test_ai_answer.yaml"
md_filepath = "./repo/results/_test.md"
md_title = "TEST"

[[tools_conf]]
name = "shell"

[[tools_conf]]
name = "human"


