llm = "gpt-4"
user_index_dir = "user_context_index"
agent_type = "zero-shot-react-description"
agent_execution_mode = "single"
eval_sentence = "var/eval_sentence/test_ai_answer.yaml"
md_filepath = "./repo/results/test.md"
md_title = "TEST"
eval_output_dir = "var/eval_sentence/result/"

[[tools_conf]]
name = "command_predictor"

[[tools_conf]]
name = "parameter_predictor"

[[tools_conf]]
name = "shell"

[[tools_conf]]
name = "user_context_github_wiki"
index_dir = "torippy01.llm_poc"
data_source = "github wiki"
llm = "gpt-3.5-turbo"
