llm = "gpt-4"
user_index_dir = "user_context_index"
agent_type = "zero-shot-react-description"
agent_execution_mode = "qa"
eval_sentence = "eval_sentence/test_ai_answer.yaml"
md_filepath = "./repo/results/test.md"
md_title = "TEST"

[[tools_conf]]
name = "command_predictor"

[[tools_conf]]
name = "parameter_predictor"

[[tools_conf]]
name = "shell"

[[tools_conf]]
name = "human"

[[tools_conf]]
name = "user_context_github_wiki"
index_dir = "torippy01.llm_poc"
data_source = "github wiki"
llm = "gpt-3.5-turbo"
