llm = "gpt-4"
user_index_dir = "user_context_index"
agent_type = "zero-shot-react-description"
agent_execution_mode = "single"
eval_sentence = "eval_sentence/test_ai_answer.yaml"
md_filepath = "./repo/results/_test.md"
md_title = "TEST"

[[tools_conf]]
name = "shell"

[[tools_conf]]
name = "command_predictor"

[[tools_conf]]
name = "parameter_predictor"

[[tools_conf]]
name = "document_user_context_predictor"
index_dir = "conflict_doc"
data_source = "document"
llm = "gpt-4"

[[tools_conf]]
name = "chat_user_context_predictor"
index_dir = "correct_chat"
data_source = "chat"
llm = "gpt-4"
