llm = "gpt-4"
user_index_dir = "user_context_index"
agent_type = "zero-shot-react-description"
interactive = false
eval_sentence = "eval_sentence/conflict.yaml"
md_filepath = "./repo/results/conflict/two_tools_two_context.md"
md_title = "two tools two contexts"

[[tools_conf]]
name = "document_user_context_predictor"
index_dir = "conflict_doc"
data_source = "document"
llm = "gpt-4"

[[tools_conf]]
name = "chat_user_context_predictor"
index_dir = "correct_chat"
data_source = "chat"
llm = "gpt-4"
